package com.sasha.adorufu.remote.packet;

import com.sasha.adorufu.AdorufuMod;
import com.sasha.adorufu.remote.PacketProcessor;
import com.sasha.adorufu.remote.RemoteDataManager;
import com.sasha.adorufu.remote.packet.events.LoginResponseEvent;

import java.util.ArrayList;

/**
 * Created by Sasha at 11:41 AM on 8/25/2018
 */
public class LoginResponsePacket extends Packet.Incoming {

    private boolean loginSuccessful;
    private String adorufuSessionId; // this is NOT your mojang session id, this is generated by the Adorufu response server and is as a verification token.

    public LoginResponsePacket(PacketProcessor processor) {
        super(processor, -1);
    }

    @Override
    public void processIncomingPacket() {
        if (loginSuccessful) {
            RemoteDataManager.INSTANCE.loggedIn = true;
            RemoteDataManager.INSTANCE.adorufuSessionId = this.adorufuSessionId;
        }
        else {
            AdorufuMod.logErr(true, "Data Server returned the \"failed login\" statuscode!");
        }
        RemoteDataManager.INSTANCE.EVENT_MANAGER.invokeEvent(new LoginResponseEvent(this));
    }

    @Override
    public void setDataVars(ArrayList<String> pckData) {
        loginSuccessful = Boolean.parseBoolean(pckData.get(0));
        if (loginSuccessful) {
            adorufuSessionId = pckData.get(1);
        }
    }
}
