package com.sasha.adorufu.remote.packet;

import com.sasha.adorufu.AdorufuMod;
import com.sasha.adorufu.remote.PacketProcessor;
import com.sasha.adorufu.remote.packet.events.RegisterResponseEvent;

import java.util.ArrayList;

/**
 * Created by Sasha at 11:41 AM on 8/25/2018
 */
public class RegisterResponsePacket extends Packet.Incoming {

    private boolean registrationSuccessful;
    private String message; // this is NOT your mojang session id, this is generated by the Adorufu response server and is as a verification token.

    public RegisterResponsePacket(PacketProcessor processor) {
        super(processor, -6);
    }

    @Override
    public void processIncomingPacket() {
        AdorufuMod.REMOTE_DATA_MANAGER.EVENT_MANAGER.invokeEvent(new RegisterResponseEvent(this));
    }

    @Override
    public void setDataVars(ArrayList<String> pckData) {
        registrationSuccessful = Boolean.parseBoolean(pckData.get(0));
        this.message = pckData.get(1);
    }
}
